### ISSUE TITLE
How to change the tab order ?

### ISSUE THREAD

**Issue by congluat** [andy-goryachev/FxDock#11]

**Comment by congluat** [comment]
![image](https://user-images.githubusercontent.com/13943402/46335223-f7179000-c650-11e8-8c6e-63194888ca2f.png)
 then i want to move DemoCPane to the top like this
![image](https://user-images.githubusercontent.com/13943402/46335261-14e4f500-c651-11e8-9c0a-07a5a6a556e9.png)

**Comment by andy-goryachev** [comment]
the component responsible for tabs is FxDockTabPane.  you should be able to get a pointer to it from your client node using, for example, FX.getAncestorOfClass() and then manually remove and reinsert nodes in the desired order with FxDockTabPane.removeTab(), FxDockTabPane.addTab() methods.

if you think there might be a case for a special method in FxDockTabPane, let me know or create a pull request.

does this answer your question?

**Comment by congluat** [comment]
I mean drag and drop function on UI. Like drag and drop tab browser in firefox/chrome

**Comment by andy-goryachev** [comment]
uh oh.  missing functionality.  thank you for noticing!

created  #12.
