### ISSUE TITLE
Load FxDock to own Pane

### ISSUE THREAD

**Issue by PawelSzymanski89** [andy-goryachev/FxDock#14]
How to load FxDock pane to own HBox for example? to get simmilar result
![Bez tytułu](https://user-images.githubusercontent.com/26041449/54814549-49487e00-4c90-11e9-87b2-c933a0aab3c1.png)

**Comment by andy-goryachev** [comment]
FxDock system is designed to be a top level container system: it loads the application settings, reconstruct all the windows and all the docked panes in the original configuration.

From the screenshot it appears you want to have a custom window - that is possible.  You may want to look at DockFramework.Generator and its createWindow() method, as shown in https://github.com/andy-goryachev/FxDock/blob/master/doc/HOWTO.md

Or perhaps you want to create a custom FxDockPane - that's a dockable container.  This too, is done via the same class, using createPane() method.

Hope I answered your question.

**Comment by andy-goryachev** [comment]
Did I answer your question?

**Comment by PawelSzymanski89** [comment]
So if i understand properly, when i want use your libray i have to rebuild my application to do your framework window as main?

**Comment by andy-goryachev** [comment]
Yes, the framework was designed to bring up all the windows in the application (that's its main function, really).  

You basically have at least three choices:

1. provide a generator for your custom windows and dockable panels (see earlier comment), or
2. reverse engineer the drag and drop code and merge it with your own code (if, for example, you only need a subset of functionality)
3. use a straightforward drag and drop to implement your own functionality

Let me know if you decide to use FxDock.
