### ISSUE TITLE
Saved window settings are overwritten after closing window

### ISSUE THREAD

**Issue by ChrisLMerrill** [andy-goryachev/FxDock#3]
I'm trying to understand how to have my layout saved when the window is closed (using the X button on the window).

In MyWindow (extends FxDockWindow) constructor, I have:
        setOnCloseRequest(event ->
            {
            saveLayout();
            });

When I start with a fresh layout (because FxDockFramework.loadLayout() returned 0), this works fine and my settings are saved.

However, when restarting with a saved layout (FxDockFramework.loadLayout()), then my window close request handler is overwritten (by FrameworkBase.registerWindow()). So, I overrode confirmClosing() in MyWindow to call saveLayout(). This works - the settings are now also saved when the layout was restored...except that immediately after the window closes, FrameworkBase.unlinkWindow calls saveLayout() again...and the saved settings now has no windows in it.

So I need some advice on how to get the layout saved when the user closes the window this way.

Thanks in advance!
Chris

(I've attached my example code)

[MyApplication.txt](https://github.com/andy-goryachev/FxDock/files/614036/MyApplication.txt)
[MyGenerator.txt](https://github.com/andy-goryachev/FxDock/files/614037/MyGenerator.txt)
[MyPane.txt](https://github.com/andy-goryachev/FxDock/files/614038/MyPane.txt)
[MyWindow.txt](https://github.com/andy-goryachev/FxDock/files/614039/MyWindow.txt)

**Comment by andy-goryachev** [comment]
Chris,
come to think of it, the layout should be saved by the framework each time the user closes a window.
let me do a quick fix.
are you using the source or the jar?
-a

**Comment by ChrisLMerrill** [comment]
I'm using the jar at the moment. It's been a while since I've used Ant, but that looks like an Ant build file, so I should be able to build from source if needed.

**Comment by ChrisLMerrill** [comment]
I built from sources. Based on your comment, I removed all of my calls to saveLayout(). It is now remembering the window position automatically.  Thanks!

**Comment by andy-goryachev** [comment]
Thank you for reporting this issue, Chris.
There is a new jar:
https://github.com/andy-goryachev/FxDock/raw/master/lib/FxDock/FxDock-0.00.03.jar

**Comment by ChrisLMerrill** [comment]
I'm sorry, but I'm still not getting the layout saved with the example that I posted. Not sure what happened - I'm pretty confident that I witnessed it working when I first built it from source. But now that I've updated to the latest (or with the ...03 jar), I do not get the layout saved. Did it work for you with my example?

**Comment by andy-goryachev** [comment]
you need to call open() instead of show():
https://github.com/andy-goryachev/FxDock/blob/master/src/demo/MyApplication.java

the framework needs to keep track of open windows, show() alone is insufficient.

**Comment by ChrisLMerrill** [comment]
Ahhh...thanks. Working now  :)

**Comment by andy-goryachev** [comment]
great!

**Comment by ChrisLMerrill** [comment]
BTW, looks like you checked in my sample into your demo tree...which I assume is a mistake you'd want to undo :>

**Comment by andy-goryachev** [comment]
removed.
thanks!
